version: '2'
services:
  db:
    image: mdillon/postgis:9.5
  web:
    build: .
    working_dir: /code
    command: python manage.py runserver 0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
